import io.restassured.http.ContentType;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import static io.restassured.RestAssured.*;
import static org.hamcrest.Matchers.*;

public class dummyApi {
    @BeforeClass
    public void setup() {
        baseURI = "https://dummyapi.io/data/v1/";
    }

    @Test
    public void testGetUserList() {
        given()
                .basePath("user")
                .param("limit", "5")
                .header("app-id", "6112dc7c3f812e0d9b6679dd")
                .when()
                .get()
                .then()
                .log().ifValidationFails()
                .assertThat()
                .statusCode(200)
                .contentType(ContentType.JSON)
                .body("data", hasSize(5))
                .body("data", not(empty()))
                .body("data[0]", hasKey("id"))
                .body("data[0]", hasKey("title"))
                .body("data[0]", hasKey("firstName"))
                .body("data[0]", hasKey("lastName"))
                .body("data[0]", hasKey("picture"))
                .body("data[2]", hasKey("id"))
                .body("data[2]", hasKey("title"))
                .body("data[2]", hasKey("firstName"))
                .body("data[2]", hasKey("lastName"))
                .body("data[2]", hasKey("picture"))
                .body("data[4]", hasKey("id"))
                .body("data[4]", hasKey("title"))
                .body("data[4]", hasKey("firstName"))
                .body("data[4]", hasKey("lastName"))
                .body("data[4]", hasKey("picture"));
    }

    @Test
    public void testGetUserById() {
        given()
                .basePath("user/60d0fe4f5311236168a10a0e")
                .header("app-id", "6112dc7c3f812e0d9b6679dd")
                .when()
                .get()
                .then()
                .log().ifValidationFails()
                .assertThat()
                .statusCode(200)
                .contentType(ContentType.JSON)
                .body("id", equalTo("60d0fe4f5311236168a10a0e"))
                .body("title", equalTo("mr"))
                .body("firstName", equalTo("Mads"))
                .body("lastName", equalTo("Andersen"))
                .body("picture", equalTo("https://randomuser.me/api/portraits/med/men/74.jpg"))
                .body("gender", equalTo("male"))
                .body("email", equalTo("mads.andersen@example.com"))
                .body("dateOfBirth", equalTo("1963-04-12T15:41:39.051Z"))
                .body("phone", equalTo("76120280"));
    }

    @Test
    public void testGetPostList() {
        given()
                .basePath("post")
                .param("limit", "5")
                .header("app-id", "6112dc7c3f812e0d9b6679dd")
                .when()
                .get()
                .then()
                .log().ifValidationFails()
                .assertThat()
                .statusCode(200)
                .contentType(ContentType.JSON)
                .body("data", hasSize(5))
                .body("data[0]", hasKey("id"))
                .body("data[0]", hasKey("image"))
                .body("data[0]", hasKey("likes"))
                .body("data[0]", hasKey("owner"))
                .body("data[0].owner", hasKey("id"))
                .body("data[0].owner", hasKey("firstName"))
                .body("data[0].owner", hasKey("lastName"))
                .body("data[0]", hasKey("tags"))
                .body("data[0].tags", not(empty()))
                .body("data[2]", hasKey("id"))
                .body("data[2]", hasKey("image"))
                .body("data[2]", hasKey("likes"))
                .body("data[2]", hasKey("owner"))
                .body("data[2].owner", hasKey("id"))
                .body("data[2].owner", hasKey("firstName"))
                .body("data[2].owner", hasKey("lastName"))
                .body("data[2]", hasKey("tags"))
                .body("data[2].tags", not(empty()))
                .body("data[3]", hasKey("id"))
                .body("data[3]", hasKey("image"))
                .body("data[3]", hasKey("likes"))
                .body("data[3]", hasKey("owner"))
                .body("data[3].owner", hasKey("id"))
                .body("data[3].owner", hasKey("firstName"))
                .body("data[3].owner", hasKey("lastName"))
                .body("data[3]", hasKey("tags"))
                .body("data[3].tags", not(empty()));
    }

    @Test
    public void testGetPostByUser() {
        given()
                .basePath("user/60d0fe4f5311236168a10a0e/post")
                .param("limit", "5")
                .header("app-id", "6112dc7c3f812e0d9b6679dd")
                .when()
                .get()
                .then()
                .log().ifValidationFails()
                .assertThat()
                .statusCode(200)
                .contentType(ContentType.JSON)
                .body("data", hasSize(5))
                .body("data[0]", hasKey("id"))
                .body("data[0]", hasKey("image"))
                .body("data[0].image", not(empty()))
                .body("data[0]", hasKey("likes"))
                .body("data[0]", hasKey("owner"))
                .body("data[0].owner.id", equalTo("60d0fe4f5311236168a10a0e"))
                .body("data[0].owner.firstName", equalTo("Mads"))
                .body("data[0].owner.lastName", equalTo("Andersen"))
                .body("data[0]", hasKey("tags"))
                .body("data[0].tags", not(empty()))
                .body("data[0].text", not(empty()))
                .body("data[0].publishDate", not(empty())).body("data[0]", hasKey("id"))
                .body("data[1]", hasKey("image"))
                .body("data[1].image", not(empty()))
                .body("data[1]", hasKey("likes"))
                .body("data[1]", hasKey("owner"))
                .body("data[1].owner.id", equalTo("60d0fe4f5311236168a10a0e"))
                .body("data[1].owner.firstName", equalTo("Mads"))
                .body("data[1].owner.lastName", equalTo("Andersen"))
                .body("data[1]", hasKey("tags"))
                .body("data[1].tags", not(empty()))
                .body("data[1].text", not(empty()))
                .body("data[1].publishDate", not(empty()))
                .body("data[4]", hasKey("id"))
                .body("data[4]", hasKey("image"))
                .body("data[4].image", not(empty()))
                .body("data[4]", hasKey("likes"))
                .body("data[4]", hasKey("owner"))
                .body("data[4].owner.id", equalTo("60d0fe4f5311236168a10a0e"))
                .body("data[4].owner.firstName", equalTo("Mads"))
                .body("data[4].owner.lastName", equalTo("Andersen"))
                .body("data[4]", hasKey("tags"))
                .body("data[4].tags", not(empty()))
                .body("data[4].text", not(empty()))
                .body("data[4].publishDate", not(empty()));
    }

    @Test
    public void testGetPostByTag() {
        given()
                .basePath("tag/dog/post")
                .param("limit", "5")
                .header("app-id", "6112dc7c3f812e0d9b6679dd")
                .when()
                .get()
                .then()
                .log().ifValidationFails()
                .assertThat()
                .statusCode(200)
                .contentType(ContentType.JSON)
                .body("data", hasSize(5))
                .body("data[0]", hasKey("id"))
                .body("data[0]", hasKey("image"))
                .body("data[0].image", not(empty()))
                .body("data[0]", hasKey("likes"))
                .body("data[0]", hasKey("owner"))
                .body("data[0].owner.firstName", not(empty()))
                .body("data[0].owner.lastName", not(empty()))
                .body("data[0]", hasKey("tags"))
                .body("data[0].tags", not(empty()))
                .body("data[0].text", not(empty()))
                .body("data[0].publishDate", not(empty())).body("data[0]", hasKey("id"))
                .body("data[1]", hasKey("image"))
                .body("data[1].image", not(empty()))
                .body("data[1]", hasKey("likes"))
                .body("data[1]", hasKey("owner"))
                .body("data[1].owner.firstName", not(empty()))
                .body("data[1].owner.lastName", not(empty()))
                .body("data[1]", hasKey("tags"))
                .body("data[1].tags", not(empty()))
                .body("data[1].text", not(empty()))
                .body("data[1].publishDate", not(empty()))
                .body("data[4]", hasKey("id"))
                .body("data[4]", hasKey("image"))
                .body("data[4].image", not(empty()))
                .body("data[4]", hasKey("likes"))
                .body("data[4]", hasKey("owner"))
                .body("data[4].owner.firstName", not(empty()))
                .body("data[4].owner.lastName", not(empty()))
                .body("data[4]", hasKey("tags"))
                .body("data[4].tags", not(empty()))
                .body("data[4].text", not(empty()))
                .body("data[4].publishDate", not(empty()));
    }

    @Test
    public void testGetCommentByPost() {
        given()
                .basePath("post/60d21bc967d0d8992e610e06/comment")
                .header("app-id", "6112dc7c3f812e0d9b6679dd")
                .when()
                .get()
                .then()
                .log().ifValidationFails()
                .assertThat()
                .statusCode(200)
                .contentType(ContentType.JSON)
                .body("data[0]", hasKey("id"))
                .body("data[0]", hasKey("message"))
                .body("data[0]", hasKey("owner"))
                .body("data[0].owner.firstName", not(empty()))
                .body("data[0].owner.lastName", not(empty()))
                .body("data[0]", hasKey("post"));
    }
}
