import io.restassured.http.ContentType;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import static io.restassured.RestAssured.*;
import static org.hamcrest.Matchers.*;

public class fakerApi {
    @BeforeClass
    public void setup() {
        baseURI = "https://fakerapi.it/api/v2/";
    }

    @Test
    public void testSingleAddress() {
        given()
                .basePath("addresses")
                .param("_quantity", "1")
                .param("_locale", "en_US")
                .contentType(ContentType.JSON)
                .when()
                .get()
                .then()
                .log().ifValidationFails()
                .assertThat()
                .statusCode(200)
                .body("status", equalTo("OK"))
                .body("locale", equalTo("en_US"))
                .body("data", hasSize(1))
                .body("data[0]", hasKey("street"))
                .body("data[0]", hasKey("city"))
                .body("data[0]", hasKey("zipcode"))
                .body("data[0]", hasKey("country"))
                .body("data[0]", hasKey("country_code"));
    }

    @Test
    public void testMultiAddresses() {
        given()
                .basePath("addresses")
                .param("_quantity", "3")
                .param("_locale", "en_US")
                .contentType(ContentType.JSON)
                .when()
                .get()
                .then()
                .log().ifValidationFails()
                .assertThat()
                .statusCode(200)
                .body("status", equalTo("OK"))
                .body("locale", equalTo("en_US"))
                .body("data", hasSize(3))
                .body("data[0]", hasKey("street"))
                .body("data[0]", hasKey("city"))
                .body("data[0]", hasKey("zipcode"))
                .body("data[0]", hasKey("country"))
                .body("data[0]", hasKey("country_code"))
                .body("data[1]", hasKey("street"))
                .body("data[1]", hasKey("city"))
                .body("data[1]", hasKey("zipcode"))
                .body("data[1]", hasKey("country"))
                .body("data[1]", hasKey("country_code"))
                .body("data[2]", hasKey("street"))
                .body("data[2]", hasKey("city"))
                .body("data[2]", hasKey("zipcode"))
                .body("data[2]", hasKey("country"))
                .body("data[2]", hasKey("country_code"));
    }

    @Test
    public void testSingleBook() {
        given()
                .basePath("books")
                .param("_quantity", "1")
                .param("_locale", "en_US")
                .contentType(ContentType.JSON)
                .when()
                .get()
                .then()
                .log().ifValidationFails()
                .assertThat()
                .statusCode(200)
                .body("status", equalTo("OK"))
                .body("locale", equalTo("en_US"))
                .body("data", hasSize(1))
                .body("data[0]", hasKey("title"))
                .body("data[0]", hasKey("author"))
                .body("data[0]", hasKey("genre"))
                .body("data[0]", hasKey("description"))
                .body("data[0]", hasKey("isbn"))
                .body("data[0]", hasKey("image"))
                .body("data[0]", hasKey("publisher"));
    }

    @Test
    public void testMultiBooks() {
        given()
                .basePath("books")
                .param("_quantity", "4")
                .param("_locale", "en_US")
                .contentType(ContentType.JSON)
                .when()
                .get()
                .then()
                .log().ifValidationFails()
                .assertThat()
                .statusCode(200)
                .body("status", equalTo("OK"))
                .body("locale", equalTo("en_US"))
                .body("data", hasSize(4))
                .body("data[0]", hasKey("title"))
                .body("data[0]", hasKey("author"))
                .body("data[0]", hasKey("genre"))
                .body("data[0]", hasKey("description"))
                .body("data[0]", hasKey("isbn"))
                .body("data[0]", hasKey("image"))
                .body("data[0]", hasKey("publisher"))
                .body("data[1]", hasKey("title"))
                .body("data[1]", hasKey("author"))
                .body("data[1]", hasKey("genre"))
                .body("data[1]", hasKey("description"))
                .body("data[1]", hasKey("isbn"))
                .body("data[1]", hasKey("image"))
                .body("data[1]", hasKey("publisher"))
                .body("data[2]", hasKey("title"))
                .body("data[2]", hasKey("author"))
                .body("data[2]", hasKey("genre"))
                .body("data[2]", hasKey("description"))
                .body("data[2]", hasKey("isbn"))
                .body("data[2]", hasKey("image"))
                .body("data[2]", hasKey("publisher"))
                .body("data[3]", hasKey("title"))
                .body("data[3]", hasKey("author"))
                .body("data[3]", hasKey("genre"))
                .body("data[3]", hasKey("description"))
                .body("data[3]", hasKey("isbn"))
                .body("data[3]", hasKey("image"))
                .body("data[3]", hasKey("publisher"));
    }

    @Test
    public void testMultipleCompanies(){
        given()
                .basePath("companies")
                .param("_quantity", "2")
                .param("_locale", "en_US")
                .contentType(ContentType.JSON)
                .when()
                .get()
                .then()
                .log().ifValidationFails()
                .assertThat()
                .statusCode(200)
                .body("status", equalTo("OK"))
                .body("locale", equalTo("en_US"))
                .body("data", hasSize(2))
                .body("data[0]", hasKey("name"))
                .body("data[0]", hasKey("email"))
                .body("data[0]", hasKey("phone"))
                .body("data[0]", hasKey("country"))
                .body("data[0]", hasKey("addresses"))
                .body("data[0].addresses[0]", hasKey("street"))
                .body("data[0].addresses[0]", hasKey("city"))
                .body("data[0].addresses[0]", hasKey("zipcode"))
                .body("data[0].addresses[0]", hasKey("country"))
                .body("data[0]", hasKey("contact"))
                .body("data[0].contact", hasKey("firstname"))
                .body("data[0].contact", hasKey("lastname"))
                .body("data[0].contact", hasKey("email"))
                .body("data[0].contact", hasKey("phone"))
                .body("data[0].contact.address", hasKey("street"))
                .body("data[0].contact.address", hasKey("city"))
                .body("data[0].contact.address", hasKey("zipcode"))
                .body("data[0].contact.address", hasKey("country"))
                .body("data[0]", hasKey("website"))
                .body("data[1]", hasKey("name"))
                .body("data[1]", hasKey("email"))
                .body("data[1]", hasKey("phone"))
                .body("data[1]", hasKey("country"))
                .body("data[1]", hasKey("addresses"))
                .body("data[1].addresses[0]", hasKey("street"))
                .body("data[1].addresses[0]", hasKey("city"))
                .body("data[1].addresses[0]", hasKey("zipcode"))
                .body("data[1].addresses[0]", hasKey("country"))
                .body("data[1]", hasKey("contact"))
                .body("data[1].contact", hasKey("firstname"))
                .body("data[1].contact", hasKey("lastname"))
                .body("data[1].contact", hasKey("email"))
                .body("data[1].contact", hasKey("phone"))
                .body("data[1].contact.address", hasKey("street"))
                .body("data[1].contact.address", hasKey("city"))
                .body("data[1].contact.address", hasKey("zipcode"))
                .body("data[1].contact.address", hasKey("country"))
                .body("data[1]", hasKey("website"));
    }

    @Test
    public void testMultipleProducts(){
        given()
                .basePath("products")
                .param("_quantity", "3")
                .param("_locale", "en_US")
                .contentType(ContentType.JSON)
                .when()
                .get()
                .then()
                .log().ifValidationFails()
                .assertThat()
                .statusCode(200)
                .body("status", equalTo("OK"))
                .body("locale", equalTo("en_US"))
                .body("data", hasSize(3))
                .body("data[0]", hasKey("name"))
                .body("data[0]", hasKey("description"))
                .body("data[0]", hasKey("price"))
                .body("data[0]", hasKey("image"))
                .body("data[0]", hasKey("net_price"))
                .body("data[0]", hasKey("categories"))
                .body("data[0].categories", not(empty()))
                .body("data[0]", hasKey("tags"))
                .body("data[0].tags", not(empty()))
                .body("data[1]", hasKey("name"))
                .body("data[1]", hasKey("description"))
                .body("data[1]", hasKey("price"))
                .body("data[1]", hasKey("image"))
                .body("data[1]", hasKey("net_price"))
                .body("data[1]", hasKey("categories"))
                .body("data[1].categories", not(empty()))
                .body("data[1]", hasKey("tags"))
                .body("data[1].tags", not(empty()))
                .body("data[2]", hasKey("name"))
                .body("data[2]", hasKey("description"))
                .body("data[2]", hasKey("price"))
                .body("data[2]", hasKey("image"))
                .body("data[2]", hasKey("net_price"))
                .body("data[2]", hasKey("categories"))
                .body("data[2].categories", not(empty()))
                .body("data[2]", hasKey("tags"))
                .body("data[2].tags", not(empty()));
    }

}
